/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "vaopen'blog",
  "description": "不能因理想遥远而放弃追求 不能因现实复杂而放弃梦想",
  "base": "/",
  "pages": [
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "type": "blog",
    "logo": "/avatar.jpg",
    "autoHideNavbar": true,
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "Category"
      },
      "tag": {
        "location": 3,
        "text": "Tag"
      }
    },
    "author": "vaopen",
    "startYear": "2020",
    "nav": [
      {
        "text": "Home",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "TimeLine",
        "link": "/TimeLine/",
        "icon": "reco-date"
      },
      {
        "text": "About",
        "link": "/About.html",
        "icon": "reco-account"
      },
      {
        "text": "Contact",
        "icon": "reco-message",
        "items": [
          {
            "text": "Github",
            "link": "https://github.com/blacklisten",
            "icon": "reco-github"
          }
        ]
      }
    ],
    "friendLink": [],
    "sidebarDepth": 1,
    "sidebar": "auto",
    "vssueConfig": {
      "platform": "github",
      "owner": "vaopen",
      "repo": "vaopen.github.io",
      "clientId": "5bae6136e7b844971fec",
      "clientSecret": "0be03091452ca01fc5ab0ed7b7346e671dc2c7d0"
    },
    "lastUpdated": "Last Updated",
    "docsRepo": "SigureMo/notev",
    "docsDir": "docs",
    "docsBranch": "master",
    "editLinks": true,
    "editLinkText": "在GitHub上编辑此页！",
    "serviceWorker": {
      "updatePopup": true
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}